### PR TITLE
Changes to apicontroller.php for OC9 compat

### PR DESCRIPTION
**Pull request by sdoconnell**
I updated to OC9 today and found that grauphel was throwing an exception on sync, 'undefined method OC_DB::beginTransaction()' (due to deprecation, I assume). I've updated apicontroller.php to resolve the problem, and now grauphel seems to test fine with OC9.0, Tomdroid 0.7.5, and Tomboy 1.15.4 on Linux.

### CODE REVIEW

**Comment by cweiske** [comment]
OC_DB is used in other places, too - they need to be fixed as well.

**Comment by sdoconnell** [comment]
It would probably be a good idea to replace any other OC_DB calls as well, but for 9.0 (at least) the ::beginTransaction() method was the only one throwing an exception. I see you're using ::executeAudited in the lib/tokenstorage.php and lib/notestorage.php , but that method still seems to work. I notice that method is also being used by a couple of other default apps (user_external and files_trashbin), and while it may be deprecated with the rest of OC_DB it's not broken (yet). For immediate 9.0 compatibility, this one fix of ::beginTransaction() seems to do it.

**Comment by cweiske** [comment]
Hm, this sounds like a regression in ownCloud.

**Comment by sdoconnell** [comment]
No, not a regression. See: http://fossies.org/dox/owncloud-9.0.0/classOC__DB.html
Apparently, OC_DB is still a valid class in OC9, it's just that ::beginTransaction() is no longer a valid method (hence the thrown exception). There is also this: https://doc.owncloud.org/api/classes/OCP.DB.html#method_beginTransaction

I don't find Owncloud's API documentation to be very helpful.

**Comment by cweiske** [comment]
The official docs link says it's deprecated. Deprecated means you should not use it anymore, but it's still there until it will be removed.

The ChangeLog https://doc.owncloud.org/server/9.0/developer_manual/app/changelog.html doesn't mention OC_DB explicitely. Maybe using `OC_*` classes was a mistake in the first place.

**Comment by cweiske** [comment]
I've replaced all OC_DB instances. Will be in 0.6.2.

Thanks for the initial patch!

**Pull request closed without merging**
