### PR TITLE
Missing standard fields (Tomboy legacy)

### PR DESCRIPTION
**Pull request by grosjo**

### CODE REVIEW

**Comment by grosjo** [comment]
I added the missing fields, but not sure how does the upgrade will execute (i.e. how to add fields in MYSQL table ?)

**Comment by grosjo** [comment]
@cweiske : I have made first release of "Tomboy Reborn"  and "Tomdroid Reborn" (see my page). (Check my github page) (using this OwnCloud/NextCloud plugin)

**Comment by cweiske** [comment]
I'm not happy with the indentation (too few or too many spaces). Apart from that it's ok.

**Comment by mwerle** [comment]
> I'm not happy with the indentation 

Add an editorconfig file with your preferred source code style?

**Comment by grosjo** [comment]
How to move forward ?

**Comment by cweiske** [comment]
Wait until I find time to review and merge the code.

**Comment by cweiske** [comment]
@grosjo Could you please fix the indentation? Click on the "files changed" tab and scroll down. You'll see that your changes have either too many spaces or too few.

**Comment by grosjo** [comment]
@cweiske  done
Also add "19" as version limit (tested on my server)

**Comment by cweiske** [comment]
Could it be that you are using tabs instead of spaces for indentation? This is not nice:


Also, the update to Nextcloud 19 shall not be done in this issue.

**Comment by grosjo** [comment]
yes , I am using tab to make it easier.
Will do a sed

**Comment by grosjo** [comment]
ok for you ?

**Comment by cweiske** [comment]
Problems with the patch:
- The database XML file was invalid (I fixed it)
- The current cursor position field was once invalid in the code

(I've fixed them all in my grosjo-more-note-fields branch)

My main question is now: Where do those fields come from? Neither the Tomboy REST API specification mention that, nor does Tomboy send those fields.
You write "missing standard fields (tomboy legacy)", but that does seem to be a lie.

**Comment by cweiske** [comment]
Closing unmerged because I didn't get a response.

**Pull request closed without merging**
